## function to access jokes
KnockKnock <- function(x) {

## This is the KKJ compendium
kkj_list <- list(
  list(name="Abby", punch="Abby birthday to you!"),
  list(name="Adam", punch="Adam up and tell me the total."),
  list(name="Adolph", punch="Adolph ball hit me in de mowf."),
  list(name="Adore", punch="Adore stands between us. Open up!"),
  list(name="Ahmed", punch="Ahmed a big mistake coming here."),
  list(name="Albie", punch="Albie darn, a funny joke!"),
  list(name="Alex", punch="Alex-plain later."),
  list(name="Alison", punch="Alison to you after you listen to me."),
  list(name="Althea", punch="Althea later, Alligator!"),
  list(name="Amanda", punch="Amanda fix the refrigerator is here."),
  list(name="Ammonia", punch="Ammonia little kid."),
  list(name="Amos", punch="A mosquito bit me."),
  list(name="Andy", punch="And he bit me again!"),
  list(name="Anita", punch="Anita ride to school."),
  list(name="Anna", punch="Anna body know some more jokes?"),
  list(name="Arthur", punch="Arthur more jokes here?"),
  list(name="Ashley", punch="Ashley (actually!), I don't know."),
  list(name="Bean", punch="Bean here for ages. What's kept you?"),
  list(name="Beezer", punch="Beezer black and yellow and make honey."),
  list(name="Before", punch="Before I freeze to death, please open the door!"),
  list(name="Ben", punch="Been knocking so long my hand hurts!"),
  list(name="Ben", punch="Ben knocking on this door all morning!"),
  list(name="Boo", punch="Please don't cry. It's just a joke!"),
  list(name="Candice", punch="Candice be the last knock-knock joke?"),
  list(name="Candy", punch="Can Dee come out and play?"),
  list(name="Canoe", punch="Canoe you lend me some money?"),
  list(name="Carl", punch="Carl get you there quicker than if you walk."),
  list(name="Cash", punch="I knew you were nuts!"),
  list(name="Cash", punch="No thanks, but I'd like some peanuts!"),
  list(name="Celeste", punch="Celeste time I'm telling you, open up."),
  list(name="Champ", punch="Champ poo your hair, it's dirty."),
  list(name="Claire", punch="Clear the way I'm coming in!"),
  list(name="Colleen", punch="Colleen up your room, its a mess!"),
  list(name="Conrad", punch="Conradulations, I used your joke!"),
  list(name="Dawn", punch="Dawn by the station, early in the morning."),
  list(name="Dewey", punch="Dewey have to keep saying all these jokes?"),
  list(name="Dewey", punch="Dewey have to listen to all this knocking!"),
  list(name="Diploma", punch="Diploma is here to fix the sink."),
  list(name="Disco", punch="Disco-nnected"),
  list(name="Disguise", punch="Disguise your boyfriend!"),
  list(name="Don Juan", punch="Don Juan to go to shool today."),
  list(name="Doris", punch="Doris locked that's why I am knocking!"),
  list(name="Doris", punch="The Door is locked, that's why I'm knocking."),
  list(name="Doughnut", punch="Doughnut worry it is just a joke!"),
  list(name="Dozen", punch="Dozen anyone want to let me in?"),
  list(name="Duane", punch="Duane the bathtub, I'm drowning!"),
  list(name="Dwayne", punch="Dwayne the bathtub, I'm dwowning!"),
  list(name="Eddie", punch="Eddie body home?"),
  list(name="Eileen", punch="Eileen'd on your bell and broke it."),
  list(name="Elsie", punch="Elsie you later."),
  list(name="Emma", punch="Am ah cracking you up?"),
  list(name="Enoch", punch="Enoch and Enoch but no one answers the door."),
  list(name="Fannie", punch="Fannie body home?"),
  list(name="Fanny", punch="These jokes aren't very fanny."),
  list(name="Felix", punch="Felix my ice cream, I'll lick his!"),
  list(name="Ferdie", punch="Ferdie last time, open up!"),
  list(name="Formosa", punch="Formosa the summer I was away on my holiday."),
  list(name="Frasier", punch="Frasier joke isn't very funny?"),
  list(name="Freddie", punch="Freddie or not, here I come."),
  list(name="General Lee", punch="Generally I do not tell jokes!"),
  list(name="Genoa", punch="Genoa any new jokes?"),
  list(name="Ghandi", punch="Ghandi cane"),
  list(name="Ghost", punch="Ghost to show you don't remember my name!"),
  list(name="Gladys", punch="Gladys is my last joke."),
  list(name="Gorilla", punch="Gorilla me a cheese sandwich."),
  list(name="Hair", punch="Hair today, gone tomorrow."),
  list(name="Harriet", punch="Harriet up. We're going to be late."),
  list(name="Harry", punch="Harry up and answer the door."),
  list(name="Hawaii", punch="I'm fine. Hawaii you?"),
  list(name="Holden", punch="Hold on, I'll go see."),
  list(name="Howard", punch="Howard was the math test today?"),
  list(name="Howie", punch="Howie going to figure this out?"),
  list(name="Howl", punch="Howl you know unless you open the door!"),
  list(name="Iam", punch="Sorry, I don't know who you are."),
  list(name="Ice cream soda", punch="Ice cream soda whole world will know how much I love you!"),
  list(name="Ida", punch="Ida know!"),
  list(name="Ima", punch="Ima commin in, so open up."),
  list(name="Ina", punch="Ina minute I'm going to knock this door down!"),
  list(name="Irish", punch="Irish you would let me in."),
  list(name="Isaac", punch="Isaac of knock-knock jokes!"),
  list(name="Isabel", punch="Isabel not working?"),
  list(name="Isabel", punch="Isabel out of order? I had to knock."),
  list(name="Isadore", punch="Is a door needed on a toilet stall!"),
  list(name="Isaiah", punch="Isaiah nothing till you open this door."),
  list(name="Island", punch="Island on your roof with my parachute."),
  list(name="Ivan", punch="Ivan workin on the railroad."),
  list(name="Jamaica", punch="Jamaica mistake?"),
  list(name="Jess", punch="Jess me, open the door."),
  list(name="Juana", punch="Juana come out and play?"),
  list(name="Justice", punch="Justice I thought. Nobody's home."),
  list(name="Justin", punch="Justin time for dinner!"),
  list(name="Justin", punch="Justin time for supper."),
  list(name="Keith", punch="Keith me, thweet heart!"),
  list(name="Ken", punch="Ken I come in? It's cold out here!"),
  list(name="Ken", punch="Ken you tell me some good knock-knock jokes?"),
  list(name="Kendall", punch="Kendall and Barbie go together."),
  list(name="Kenya", punch="Kenya guess hwo it is?"),
  list(name="Ketchup", punch="Ketchup with me an you'll find out!"),
  list(name="Kip", punch="Kip your hands off of me!"),
  list(name="Leaf", punch="Leaf me alone!"),
  list(name="Lena", punch="Lena little closer and I'll tell you."),
  list(name="Les", punch="Les hear another knock-knock joke!"),
  list(name="Li'l ol'lady", punch="I didn't know you could yodel."),
  list(name="Lionel", punch="Lionel bite you if you put your head in its mouth!"),
  list(name="Luke", punch="Like through the keyhole and you'll see."),
  list(name="Luke", punch="Luke out! Here comes another knock-knock joke."),
  list(name="Lydia", punch="The lid a your trash can just blew off!"),
  list(name="Mae", punch="Mae be i'll tell you and Mae be I won't."),
  list(name="Manuel", punch="Manuel be sorry if you don't let him in."),
  list(name="Marietta", punch="Marietta whole cake!"),
  list(name="Marilyn", punch="Marilyn is a state just north of Virginia."),
  list(name="Marsh", punch="Marshmallow!"),
  list(name="Max", punch="Max no difference to you, just let me in."),
  list(name="Mikey", punch="Mikey won't fit in this lock."),
  list(name="Nadia", punch="Nadia head if you understand what I'm saying."),
  list(name="Needle", punch="Needle little more time."),
  list(name="Noah", punch="Noah don't know who you are either!"),
  list(name="Noah", punch="Noah good place to find more jokes?"),
  list(name="Norma Lee", punch="Norma Lee I don't go around knocking on people's doors, but I just had to meet you."),
  list(name="Norma Lee", punch="Normally I ring the doorbell!"),
  list(name="Norway", punch="Norway will I leave till you open this door!"),
  list(name="Nuisance", punch="Any nuisance I saw you yesterday?"),
  list(name="Olive", punch="Olive right next door to you."),
  list(name="Olive", punch="Olive you!"),
  list(name="Oliver", punch="Oliver you there are bugs!"),
  list(name="Orange", punch="Orange you going to open this door?"),
  list(name="Ozzie", punch="Ozzie you later."),
  list(name="Pecan", punch="Pecan me again and I'll tell the teacher!"),
  list(name="Phillip", punch="Phillip my glass, will you please?"),
  list(name="Phillip", punch="Phillip the gas tank, I'm running low."),
  list(name="Phyllis", punch="Phyllis in on the news, please."),
  list(name="Quack", punch="Quack another bad joke and I'm leaving."),
  list(name="Qualify", punch="I'll qualify ever want to tell you."),
  list(name="Quarter", punch="Quarter with her hand in the cookie jar!"),
  list(name="Quebec", punch="Quebec to the end of the line!"),
  list(name="Quilt", punch="Quilt-ee as charged."),
  list(name="Raleigh", punch="Raleigh `round the flag, boys!"),
  list(name="Reed", punch="Reed between the lines."),
  list(name="Rhoda", punch="Rhoda horse yesterday and fell off."),
  list(name="Rosa", punch="Rosa corn grow in the field."),
  list(name="Rufus", punch="Rufus leaking and I'm getting wet!"),
  list(name="Rufus", punch="Your roof is on fire!"),
  list(name="Sadie", punch="Sadie magic words and I'll tell you."),
  list(name="Safari", punch="Safari, so good."),
  list(name="Sally", punch="Sally-brate the moments of your life!"),
  list(name="Sam", punch="Sam person who knocked on the door last time!"),
  list(name="Sarah", punch="Sarah doctor in the house?"),
  list(name="Sarah", punch="Sarah reason you're not laughing?"),
  list(name="Shirley", punch="Shirley you must know me by now?"),
  list(name="Stan", punch="Stan back, I think I'm going to sneeze!"),
  list(name="Surely", punch="Surely you can open the door!"),
  list(name="Tank", punch="You're welcome!"),
  list(name="Tennis", punch="Tennis five plus five."),
  list(name="Thatcher", punch="Thatcher was a funny joke!"),
  list(name="Thea", punch="Thea later, alligator!"),
  list(name="Theodore", punch="Open Theodore an let me in."),
  list(name="Theodore", punch="Theodore wasn't open so I knocked!"),
  list(name="Thermos", punch="Thermos be a better knock-knock joke than this!"),
  list(name="Tinker Bell", punch="Tinker Bell is out of order."),
  list(name="Toby", punch="To be, or not to be. That is the question!"),
  list(name="Tom Sawyer", punch="Tom saw yer underwear!"),
  list(name="Tuna", punch="Tuna piano and it will sound better."),
  list(name="Udder", punch="Udder people let me in, why don't you?"),
  list(name="Uganda", punch="Uganda get away with this!"),
  list(name="Uriah", punch="Kepp Uriah on the ball!"),
  list(name="Usher", punch="Usher wish you would let me in."),
  list(name="Utta", punch="Utta sight, Utta mind."),
  list(name="Van", punch="Van can I see you again?"),
  list(name="Vaughn", punch="Vaughn day my prince will come."),
  list(name="Venice", punch="Venice your mother coming home?"),
  list(name="Vera", punch="Vera few people think these jokes are funny."),
  list(name="Verdi", punch="Verdi been all day?"),
  list(name="Vida", punch="Vida you talk like that!"),
  list(name="Viola", punch="Viola sudden don't you know me?"),
  list(name="Violet", punch="Violet the cat out of the bag?"),
  list(name="Voodoo", punch="Voodoo you think you are?"),
  list(name="Voodoo", punch="Voodoo you think you are?"),
  list(name="Waddle", punch="Waddle you give me if I go away?"),
  list(name="Wade", punch="Wade down upon the river."),
  list(name="Wah", punch="Gee, I didn't know you'd get so excited about it!"),
  list(name="Wanda", punch="Wanda where I put my car keys!"),
  list(name="Warrior", punch="Warrior been all my life?"),
  list(name="Watson", punch="Watson TV tonight?"),
  list(name="Wayne", punch="Wayne, Wayne, go away, come again another day!"),
  list(name="Wendy", punch="Wendy last time you took a bath?"),
  list(name="Wendy", punch="Wendy the last time you took a bath?"),
  list(name="Who", punch="Did you hear an owl?"),
  list(name="Will", punch="Will you let me in, its cold out here."),
  list(name="X", punch="X for breakfast."),
  list(name="Xavier", punch="Xavier breath, I'm not leaving!"),
  list(name="Xavier", punch="Xavier money for a rainy day."),
  list(name="Xenia", punch="Xenia playing ball at the park."),
  list(name="Ya", punch="I didn't know you were a cowboy!"),
  list(name="Yacht", punch="Yacht a know me by now!"),
  list(name="Yellow", punch="Yellow my name is Katie."),
  list(name="Yolanda", punch="Yolanda me some money?"),
  list(name="You", punch="Did you call me?"),
  list(name="Zany", punch="Zany body home?"),
  list(name="Zeke", punch="Zeke and you shall find!"),
  list(name="Zippy", punch="Mrs. Zippy"),
  list(name="Zizi", punch="Zizi when you know how."),
  list(name="Zone", punch="Zone dog bit him in the leg!"),
  list(name="Catsup", punch="Catsup a tree and she won't come down!"),
  list(name="Claws", punch="Claws the door behind us!"),
  list(name="Arthur", punch="Arthur any more dogs out there?"),
  list(name="Ken", punch="Ken I bring my dog inside?"),
  list(name="Whale", punch="Whale will you let me in or won't you?"),
  list(name="Alpaca", punch="Alpaca the trunk, you pack-a the suitcase."),
  list(name="Lion", punch="I'm lion on your doorstep, ipen up!"),
  list(name="Goat", punch="Goat to the door and find out."),
  list(name="Aware", punch="Aware, aware have my little sheep gone?"),
  list(name="Snakeskin", punch="Snakes-kin bite, but we'd rather run away."),
  list(name="Ants", punch="Ants in your pants will make you dance."),
  list(name="Honeybee", punch="Honeybee a dear and get me a glass of beer."),
  list(name="Icy", punch="Icy a polar bear up ahead."),
  list(name="Berry", punch="Berry nice to meet you!"),
  list(name="Eye", punch="Eye know you took a bite out of my apple!"),
  list(name="Ben", punch="Ben out picking apples."),
  list(name="Water", punch="Water you doing with my hot chocolate?"),
  list(name="Butter", punch="Butter let me in!"),
  list(name="Ham", punch="Ham and eggs for breakfast."),
  list(name="Beehive", punch="Beehive yourself or you'll get in trouble!"),
  list(name="Bee", punch="Bee nice and let me in."),
  list(name="Wheel", punch="Wheel you share an ice cream with me?"),
  list(name="Radio", punch="Redio not, here I come!"),
  list(name="Wood", punch="Wood you be quiet?"),
  list(name="Randy", punch="Randy mile in under four minutes."))


  if (missing(x))
    x <- sample.int(length(kkj_list), 1)
  kkj <- kkj_list[[x[1]]]
  KnockKnockJoke(name=kkj$name, punch=kkj$punch)
}
